### ISSUE TITLE
SyntaxError: invalid syntax

### ISSUE THREAD

**Issue by igorspp** [marbl/bambus3#11]
Hi,

After installing everything I get:

```
> python run.py -h

  File "run.py", line 35
    print('Networkx ' + version + ' found', file=sys.stderr)
                                                ^
SyntaxError: invalid syntax
```

I am using python 2.7.15, I have used conda to install the dependencies, and did the compiling as per the GitHub Wiki instructions.
These are the commands I have used to set everything up:

```
conda create -n metacarvel python=2.7
conda activate metacarvel
conda install -c bioconda samtools bedtools
pip install networkx==1.10
conda install numpy
git clone --recursive  https://github.com/marbl/MetaCarvel.git
cd MetaCarvel
bash install.sh
```

As far as I can tell nothing went wrong during compiling. 
Does anyone have any idea what might be going on?

Igor

**Comment by igorspp** [comment]
So if I understood correctly the syntax used for 'print' is in python3 but according to the instructions MetaCarvel requires python2.7?
If I add this to run.py:

`from __future__ import print_function`

It seems to solve the backward compatibility issue.

**Comment by igorspp** [comment]
I'm still running into errors and I'm not sure how much is related to my original issue.
If someone could comment on I would be grateful...

**Comment by ghuryejay** [comment]
MetaCarvel requires python3. What's the error if you use that?

**Comment by igorspp** [comment]
If I use python3.9:

```
> python MetaCarvel/run.py -a TEST-DATA/contigs.fasta -m TEST-DATA/alignment.bam -d output

Traceback (most recent call last):
  File "/projappl/project_2000577/MetaCarvel/run.py", line 28, in main
    import networkx
  File "/scratch/project_2000577/miniconda3/envs/metacarvel2/lib/python3.9/site-packages/networkx/__init__.py", line 84, in <module>
    import networkx.generators
  File "/scratch/project_2000577/miniconda3/envs/metacarvel2/lib/python3.9/site-packages/networkx/generators/__init__.py", line 5, in <module>
    from networkx.generators.classic import *
  File "/scratch/project_2000577/miniconda3/envs/metacarvel2/lib/python3.9/site-packages/networkx/generators/classic.py", line 21, in <module>
    from networkx.algorithms.bipartite.generators import complete_bipartite_graph
  File "/scratch/project_2000577/miniconda3/envs/metacarvel2/lib/python3.9/site-packages/networkx/algorithms/__init__.py", line 12, in <module>
    from networkx.algorithms.dag import *
  File "/scratch/project_2000577/miniconda3/envs/metacarvel2/lib/python3.9/site-packages/networkx/algorithms/dag.py", line 2, in <module>
    from fractions import gcd
ImportError: cannot import name 'gcd' from 'fractions' (/scratch/project_2000577/miniconda3/envs/metacarvel2/lib/python3.9/fractions.py)
```

This seems to be  a known issue: [https://github.com/networkx/networkx/issues/4335](url)

I had to upgrade networkx to v2.5:

```
> pip install --upgrade networkx

Requirement already satisfied: networkx in /scratch/project_2000577/miniconda3/envs/metacarvel2/lib/python3.9/site-packages (1.11)
Collecting networkx
  Downloading networkx-2.5-py3-none-any.whl (1.6 MB)
     |████████████████████████████████| 1.6 MB 4.8 MB/s
Requirement already satisfied: decorator>=4.3.0 in /scratch/project_2000577/miniconda3/envs/metacarvel2/lib/python3.9/site-packages (from networkx) (4.4.2)
Installing collected packages: networkx
  Attempting uninstall: networkx
    Found existing installation: networkx 1.11
    Uninstalling networkx-1.11:
      Successfully uninstalled networkx-1.11
Successfully installed networkx-2.5
```

And now things seem to work.
Maybe you should update the instructions [https://github.com/marbl/MetaCarvel/wiki/2.-Installing-the-software](url) to the correct python 3.9 instead of 2.7.x and networkx 2.5 instead of <1.11.

**Comment by hsmurali** [comment]
MetaCarvel works with Python 3 and latest versions of NetworkX. Updating to the latest versions should ix the bug.

**Comment by flutterq** [comment]
All Possible workind solution [[Solved] ‘Syntax Error: invalid syntax’ for no apparent reason](https://flutterq.com/syntax-error-invalid-syntax/)

**Comment by linehammer** [comment]
I think its because in Python 3, print statement has been replaced with a print() function, with keyword arguments to replace most of the special syntax of the old print statement.  But if you write this in a program and someone using Python 2.x tries to run it, they will get an error. To avoid this, it is a good practice to import print function:

`from __future__ import print_function`

Now your code works on both [python2 and python3](http://net-informations.com/python/intro/2vs3.htm)
