### ISSUE TITLE
Paired reads recognition in libcorrect

### ISSUE THREAD

**Issue by manu-script** [marbl/bambus3#12]
Hi,
I was curious as to how MetaCarvel was recognizing the correct read pairs after mapping in single-end mode. I see that after converting the read name sorted bam to bed file, the `parse_bed` function in the `libcorrect.cpp` file is recognising the pairs using the `/1` `/2` suffix in the read names or by matching the entire read names in the following code snippet from line 61 to 84:

```
if(read[read.length()-2] == '/')
		{
			if(read[read.length() -1 ] == '1')
			{
				first_in_pair[read.substr(0,read.length()-2)] = rec;
			}	
			else
			{	
				second_in_pair[read.substr(0,read.length()-2)] = rec;
			}
		}
		else
		{
			if(seen.find(read) == seen.end())
		    {
		    	first_in_pair[read] = rec;
				seen[read] = true;
		    }
		    else
		    {
				second_in_pair[read] = rec;
		    }

		}

```

I was wondering if this strategy would fail to recognise the correct read pairs in the following two scenarios:

1. When bowtie is run with the `--no-unal`  parameter to output only the aligned reads to the sam file.
2. When the read pairs are represented by `1:` `2:` format that is very common now instead of `/1` `/2` suffix.

Please let me know if that's correct.

Thank you,
Manu

**Comment by hsmurali** [comment]
Hi Manu, 

Thank you for bringing this up. 

1. MetaCarvel works when reads are aligned using Bowtie2 with ```--no-unal``` parameter. We recommend mapping each of the read pairs in single end mode and MetaCarvel estimates the library sizes by looking at reads where both pairs are mapped to the same contig.
2. For the read naming convention,  the current version of MetaCarvel assumes the read pairs are identified by the ```/1``` and ```/2``` naming convention. We are working on fixing to support other common tags such as ```:1```, ``` :2```  and ```.1``` and ```.2```.

**Comment by manu-script** [comment]
Great! Thanks for the clarification.
