### ISSUE TITLE
Issue with repeat option.

### ISSUE THREAD

**Issue by tiendu** [marbl/bambus3#15]
I was looping the command through for loop and found this error.

```
> for i in {1..7}; do python run.py --assembly /media/tien/E842296E42294324/bh/trim_reads/contigs/BH${i}_contigs.fa --mapping /media/tien/E842296E42294324/bh/trim_reads/mapping/BH${i}.bam --dir /media/tien/E842296E42294324/bh/trim_reads/scaffolds/BH${i} -r true -v true -k true; done
> Networkx 2.8.4 found
> Sun Jun 26 16:31:58 2022:Starting scaffolding..
> Sun Jun 26 16:33:10 2022:Finished conversion
> Sun Jun 26 16:33:10 2022:Started generating links between contigs
> finished conversion
> Size of First Map = 2554804
> Size of Second Map = 2393077
> Sum = 9.17633e+08
> Size = 1790143
> Mean = 512.603
> Stdev = 2823.34
> Sun Jun 26 16:33:29 2022:Finished conversion
> Sun Jun 26 16:33:29 2022:Started generating links between contigs
> Size of First Map = 2554804
> Size of Second Map = 2393077
> Sum = 9.17633e+08
> Size = 1790143
> Mean = 512.603
> Stdev = 2823.34
> Sun Jun 26 16:34:55 2022:Finished generating links between contigs
> Sun Jun 26 16:34:55 2022:Started bulding of links between contigs
> Sun Jun 26 16:35:05 2022:Finished generating links between contigs
> Sun Jun 26 16:35:05 2022:Started bulding of links between contigs
> Sun Jun 26 16:35:05 2022:Started finding and removing repeats
> invalidating...k141_127565
> /home/tien/miniconda3/lib/python3.9/site-packages/numpy/core/fromnumeric.py:3432: RuntimeWarning: Mean of empty slice.
>   return _methods._mean(a, axis=axis, dtype=dtype,
> /home/tien/miniconda3/lib/python3.9/site-packages/numpy/core/_methods.py:190: RuntimeWarning: invalid value encountered in double_scalars
>   ret = ret.dtype.type(ret / rcount)
> /home/tien/miniconda3/lib/python3.9/site-packages/numpy/core/_methods.py:265: RuntimeWarning: Degrees of freedom <= 0 for slice
>   ret = _var(a, axis=axis, dtype=dtype, out=out, ddof=ddof,
> /home/tien/miniconda3/lib/python3.9/site-packages/numpy/core/_methods.py:223: RuntimeWarning: invalid value encountered in divide
>   arrmean = um.true_divide(arrmean, div, out=arrmean, casting='unsafe',
> /home/tien/miniconda3/lib/python3.9/site-packages/numpy/core/_methods.py:257: RuntimeWarning: invalid value encountered in double_scalars
>   ret = ret.dtype.type(ret / rcount)
> Traceback (most recent call last):
>   File "/home/tien/MetaCarvel/repeat_filter.py", line 65, in <module>
>     p_degree = np.percentile(list(contig_degree.values()),75)
>   File "<__array_function__ internals>", line 180, in percentile
>   File "/home/tien/miniconda3/lib/python3.9/site-packages/numpy/lib/function_base.py", line 4166, in percentile
>     return _quantile_unchecked(
>   File "/home/tien/miniconda3/lib/python3.9/site-packages/numpy/lib/function_base.py", line 4424, in _quantile_unchecked
>     r, k = _ureduce(a,
>   File "/home/tien/miniconda3/lib/python3.9/site-packages/numpy/lib/function_base.py", line 3725, in _ureduce
>     r = func(a, **kwargs)
>   File "/home/tien/miniconda3/lib/python3.9/site-packages/numpy/lib/function_base.py", line 4593, in _quantile_ureduce_func
>     result = _quantile(arr,
>   File "/home/tien/miniconda3/lib/python3.9/site-packages/numpy/lib/function_base.py", line 4699, in _quantile
>     take(arr, indices=-1, axis=DATA_AXIS)
>   File "<__array_function__ internals>", line 180, in take
>   File "/home/tien/miniconda3/lib/python3.9/site-packages/numpy/core/fromnumeric.py", line 190, in take
>     return _wrapfunc(a, 'take', indices, axis=axis, out=out, mode=mode)
>   File "/home/tien/miniconda3/lib/python3.9/site-packages/numpy/core/fromnumeric.py", line 57, in _wrapfunc
>     return bound(*args, **kwds)
> IndexError: cannot do a non-empty take from an empty axes.
> Sun Jun 26 16:35:10 2022: Failed to find repeats, terminating scaffolding....
> b''
> finished conversion
> ^CTraceback (most recent call last):
>   File "/home/tien/MetaCarvel/run.py", line 187, in <module>
>     main()
>   File "/home/tien/MetaCarvel/run.py", line 91, in main
>     p = subprocess.check_output(cwd+'/bundler -l '+ args.dir+'/contig_links -o ' + args.dir+'/bundled_links + -b '+args.dir+'/bundled_graph.gml -c '+str(args.bsize), shell=True)
>   File "/home/tien/miniconda3/lib/python3.9/subprocess.py", line 424, in check_output
>     return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
>   File "/home/tien/miniconda3/lib/python3.9/subprocess.py", line 507, in run
>     stdout, stderr = process.communicate(input, timeout=timeout)
>   File "/home/tien/miniconda3/lib/python3.9/subprocess.py", line 1121, in communicate
>     stdout = self.stdout.read()
> KeyboardInterrupt
> [2]   Exit 1                  python run.py -a /media/tien/E842296E42294324/bh/trim_reads/contigs/BH${i}_contigs.fa -m /media/tien/E842296E42294324/bh/trim_reads/mapping/BH${i}.bam -d /media/tien/E842296E42294324/bh/trim_reads/scaffolds/BH${i} -r true -v true -k true
```

**Comment by hsmurali** [comment]
Could you please tell me how many contigs, with length greater than 500 base pairs,  there are, in the assembly? Would it be possible to share the output of oriented.gml file?

**Comment by tiendu** [comment]
Hi Harihara,

There are 775,695 contigs with length larger than 500 out of 2,054,472. Also, I have rerun it without the for loop and everything seems fine except now I'm stuck in the invalidating step. So it goes like this and there is no response even though it's been 12 hrs.
...
invalidating...k141_502397
invalidating...k141_1263860
invalidating...k141_1379505
invalidating...k141_1497228
invalidating...k141_30128
invalidating...k141_765138
invalidating...k141_407566
invalidating...k141_407566

[oriented.zip](https://github.com/marbl/MetaCarvel/files/8987913/oriented.zip)

Sorry but I have deleted the files for the for loop run. I only have the oriented.gml for this run. Would you please check this instead?

Thanks,

Tien

**Comment by hsmurali** [comment]
Hi Tien, 

Metacarvel assigns orientation to contigs after repeat removal and it is the most expensive step.  For large assemblies, it could take over a day to scaffold. 

<img width="485" alt="Screen Shot 2022-06-26 at 9 49 25 PM" src="https://user-images.githubusercontent.com/42724690/175845855-37f874c1-9954-4ce9-aeb5-3fe23cd41907.png">

Here is an example from one of our own experiments and if you could see the orientation assignment took the most time. I'd appreciate if you could just keep it running and let Metacarvel terminate. Kindly let me know if you've more questions. I appreciate your patience. 

We are working on making Metacarvel faster by incorporating better heuristics for assigning orientation. 

Also, I think the repeat detection works fine, 

<img width="1366" alt="Screen Shot 2022-06-26 at 9 51 40 PM" src="https://user-images.githubusercontent.com/42724690/175846044-94224e83-f6c4-41f7-980b-9b32feacc6f8.png">

As you can spot from the above snippet the number of nodes in the graph dropped from 775695 to 333243 which is an artifact of repeat removal. 

Kindly let me know if I can be any assistance. 

Thank you. 

Harihara

**Comment by tiendu** [comment]
Thanks for the info Harihara. It's a relief to know it's still running.

Also, I'm working on getting it to a loop. It's weird because every time I put it into the loop, the error popped up.

**Comment by hsmurali** [comment]
I assume the loop is for processing multiple files. In that case, it is likley the error happens in one of the many samples you have. In that case, please send me the error logs for those samples, Metacarvel fails. 

Thank you.

**Comment by tiendu** [comment]
It's fine this time. It seems like if there is an error, one should clear the bed file and all the files that were created in that run, then rerun.

My run was finished Harihara. The MetagenomeScope included in the program uses Python 2.7. It might be a bit of a problem. In the future update, could you make a tutorial on using the latest MetagenomeScope? That'd be greatly helpful.

**Comment by hsmurali** [comment]
The metagenomescope is used to visualize the graph scaffolds. We have updated metagenome scope to work with python3. I'll add a fix to metacarvel to seamlessly work with metacarvel. 

We also would like to draw your attention to https://github.com/marbl/binnacle, which is a tool to bin the graph scaffolds produced by metacarvel. Just dropping it here incase you are interested.

**Comment by hsmurali** [comment]
I am closing this issue since your problem has been resolved. Thanks!
