### ISSUE TITLE
Install problem

### ISSUE THREAD

**Issue by wwood** [marbl/bambus3#3]
Hi,

Tried to install MetaCarvel according to the instructions, but ran into this error:
```
$ centrality
centrality: /usr/lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.18' not found (required by centrality)
centrality: /usr/lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.19' not found (required by centrality)
```
It seems that centrality and spqr are binaries that are not generated during the `make` process (they are bundled pre-compiled in the git repo), and attempting to build them fails due to missing headers (from networkit?). Is there some recommended way to compile them? metacarvel is python-2 while networkit is python-3, I think?

We have gotten it working by writing wrapper scripts that add `LD_LIBRARY_PATH` etc, but it would be great to be able to compile that our install proceeded correctly. Is there some way to test our install? There wasn't a `check` target in the makefile.

Thanks, ben

**Comment by wwood** [comment]
Also, what is the software license of MetaCarvel? I couldn't see reference to any.

**Comment by skoren** [comment]
It looks like you're right, the make file is not building those binaries and they are built using a newer GCC than you have on your system. @machinegun you can probably get the binaries to work by building in a VM with an old OS and new GCC (see: https://pmelsted.wordpress.com/2015/10/14/building-binaries-for-bioinformatics/)

@wwood The missing libraries should all be in C++, not python so it looks like you'd need NetworkKit (https://networkit.iti.kit.edu/get_started.html, you don't need the Python part only the C++) and ODGF (https://github.com/ogdf/ogdf).
